export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

//login

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
